### PR TITLE
ADD datadog notifcation

### PR DESCRIPTION
**Pull request by phoolish**
First pass

### CODE REVIEW

**Comment by pturley** [comment]
this looks neat, but I dont feel qualified to approve. I will leave that to @ahorner

**Comment by phoolish** [comment]
@pturley I don't think I'm qualified to create the PR :flushed:

**Comment by rdunlop** [comment]
@phoolish I'm interested in pairing with you on this, if you'd like

**Comment by phoolish** [comment]
@rdunlop I would love to, but I am strapped for time this week and I disappear for the rest of the month next week.

**Comment by rdunlop** [comment]
@ahorner Updated.

**Comment by rdunlop** [comment]
I don't know why hound is complaining now, ...it's just frustrating me.

**Comment by ahorner** [comment]
It looks like HoundCI it's running on a newer version of rubocop, so the cop names have changed. I'll merge this and deal with updating the rubocop configuration separately.

**Pull request merged**
